"""Single place for all data paths. TESTER: edit DATA_DIR to point to where you downloaded
the datasets (see docs/01_data_sources.md). Everything else is derived from it.

The defaults point to the development machine so the pipeline runs as-is there; on any other
machine, download the data per docs/01_data_sources.md and set DATA_DIR to your data root.
"""
import pathlib

REPO = pathlib.Path(__file__).resolve().parent

# Raw data lives inside this repo under data/ (gitignored, so not pushed to GitHub).
# Download the files per docs/01_data_sources.md into data/ keeping the same subfolders.
# To point at data stored elsewhere, override DATA_DIR here.
DATA_DIR = REPO / "data"
ARTIFACTS = REPO / "artifacts"
ARTIFACTS.mkdir(exist_ok=True)
# harmonised artifacts are shipped in the repo and regenerated by src/harmonisation.py
HARMONISED_DIR = ARTIFACTS / "harmonised"
HARMONISED_DIR.mkdir(exist_ok=True)

# raw datasets (see docs/01_data_sources.md for download links)
BER_CSV = REPO / "BERPublicSearch/BERPublicsearch.txt"
SAPS_CSV = DATA_DIR / "irish_buildings/d06_cso_census/saps_2022/SAPS_2022_Small_Area_UR_171024.csv"
SAPS_GPKG = DATA_DIR / "irish_buildings/d06_cso_census/saps_2022_boundaries/Small_Area_National_Statistical_Boundaries_2022_Ungeneralised_view_-7354763930310470674.gpkg"
JRC_XLSX = DATA_DIR / "europe/curves/d19_jrc_huizinga_curves/copy_of_global_flood_depth-damage_functions__30102017.xlsx"
MIDDLESEX_CSV = DATA_DIR / "europe/curves/d20_middlesex_irish_curves/middlesex_irish_residential.csv"
DEM_TIF = DATA_DIR / "irish_hazard/d24_copernicus_dem/dem_dublin_itm.tif"
COASTAL_TIF = DATA_DIR / "irish_hazard/d03_coastal_hazard/ncfhm_itm_dep_c_c_0100_f_00.tif"
FLUVIAL_DIR = DATA_DIR / "irish_hazard/d02_nifm_fluvial"
RAINFALL_TXT = DATA_DIR / "irish_context/d08_met_eireann/IE_RR_8110_V2.txt"

# harmonised inputs
CURVE_FAMILY = HARMONISED_DIR / "reference_curve_family.csv"
EXPOSURE_PROFILES = HARMONISED_DIR / "irish_exposure_ber_profiles.csv"
